config/routes.rb
Rails.application.routes.draw do
  resources :bitcoins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bitcoin.rb
class Bitcoin < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bitcoins_controller.rb
class BitcoinsController < ApplicationController
  before_action :set_bitcoin, only: [:show, :edit, :update, :destroy]

  # GET /bitcoins
  # GET /bitcoins.json
  def index
    @bitcoins = Bitcoin.all
  end

  # GET /bitcoins/1
  # GET /bitcoins/1.json
  def show
  end

  # GET /bitcoins/new
  def new
    @bitcoin = Bitcoin.new
  end

  # GET /bitcoins/1/edit
  def edit
  end

  # POST /bitcoins
  # POST /bitcoins.json
  def create
    @bitcoin = Bitcoin.new(bitcoin_params)

    respond_to do |format|
      if @bitcoin.save
        format.html { redirect_to @bitcoin, notice: 'Bitcoin was successfully created.' }
        format.json { render :show, status: :created, location: @bitcoin }
      else
        format.html { render :new }
        format.json { render json: @bitcoin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bitcoins/1
  # PATCH/PUT /bitcoins/1.json
  def update
    respond_to do |format|
      if @bitcoin.update(bitcoin_params)
        format.html { redirect_to @bitcoin, notice: 'Bitcoin was successfully updated.' }
        format.json { render :show, status: :ok, location: @bitcoin }
      else
        format.html { render :edit }
        format.json { render json: @bitcoin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bitcoins/1
  # DELETE /bitcoins/1.json
  def destroy
    @bitcoin.destroy
    respond_to do |format|
      format.html { redirect_to bitcoins_url, notice: 'Bitcoin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bitcoin
      @bitcoin = Bitcoin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bitcoin_params
      params.require(:bitcoin).permit(:blockchain, :lixiaolai)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bitcoins_helper.rb
module BitcoinsHelper
end

app/views/bitcoins/_form.html.erb
<%= form_for(bitcoin) do |f| %>
  <% if bitcoin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bitcoin.errors.count, "error") %> prohibited this bitcoin from being saved:</h2>

      <ul>
      <% bitcoin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :blockchain %>
    <%= f.text_field :blockchain %>
  </div>

  <div class="field">
    <%= f.label :lixiaolai %>
    <%= f.text_area :lixiaolai %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bitcoins/edit.html.erb
<h1>Editing Bitcoin</h1>

<%= render 'form', bitcoin: @bitcoin %>

<%= link_to 'Show', @bitcoin %> |
<%= link_to 'Back', bitcoins_path %>

app/views/bitcoins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bitcoins</h1>

<table>
  <thead>
    <tr>
      <th>Blockchain</th>
      <th>Lixiaolai</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bitcoins.each do |bitcoin| %>
      <tr>
        <td><%= bitcoin.blockchain %></td>
        <td><%= bitcoin.lixiaolai %></td>
        <td><%= link_to 'Show', bitcoin %></td>
        <td><%= link_to 'Edit', edit_bitcoin_path(bitcoin) %></td>
        <td><%= link_to 'Destroy', bitcoin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bitcoin', new_bitcoin_path %>

app/views/bitcoins/new.html.erb
<h1>New Bitcoin</h1>

<%= render 'form', bitcoin: @bitcoin %>

<%= link_to 'Back', bitcoins_path %>

app/views/bitcoins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Blockchain:</strong>
  <%= @bitcoin.blockchain %>
</p>

<p>
  <strong>Lixiaolai:</strong>
  <%= @bitcoin.lixiaolai %>
</p>

<%= link_to 'Edit', edit_bitcoin_path(@bitcoin) %> |
<%= link_to 'Back', bitcoins_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blockchain</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>